version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=aitrix_db
      - POSTGRES_USER=aitrixuser
      - POSTGRES_PASSWORD=aitrix2022
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    ports:
      - "5433:5432"

  web:
    build: ./
    restart: always
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
